Create DataFrame (Pandas)

In [1]:
import pandas as pd

In [3]:
Data=pd.read_csv("/content/data.csv")
Data

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,46120
11910,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,56670
11911,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50620
11912,Acura,ZDX,2013,premium unleaded (recommended),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50920
11913,Lincoln,Zephyr,2006,regular unleaded,221.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Sedan,26,17,61,28995

In [5]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Make               11914 non-null  object
 1   Model              11914 non-null  object
 2   Year               11914 non-null  int64
 3   Engine Fuel Type   11911 non-null  object
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11884 non-null  float64
 6   Transmission Type  11914 non-null  object
 7   Driven_Wheels      11914 non-null  object
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object
 10  Vehicle Size       11914 non-null  object
 11  Vehicle Style      11914 non-null  object
 12  highway MPG        11914 non-null  int64
 13  city mpg           11914 non-null  int64
 14  Popularity         11914 non-null  int64
 15  MSRP               11914 non-null  int64
dtypes: float64(3), int64(5), object(8)
memory usage: 1.5+ MB

In [17]:
Data = Data.drop (["Engine Fuel Type","Market Category",
                  "Number of Doors","Vehicle Style",
                  "Popularity","Vehicle Size"],axis = 1,implace = True)
Data.head()

TypeError: DataFrame.drop() got an unexpected keyword argument 'implace'

In [18]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Make               11914 non-null  object
 1   Model              11914 non-null  object
 2   Year               11914 non-null  int64
 3   Engine HP          11845 non-null  float64
 4   Engine Cylinders   11884 non-null  float64
 5   Transmission Type  11914 non-null  object
 6   Driven_Wheels      11914 non-null  object
 7   highway MPG        11914 non-null  int64
 8   city mpg           11914 non-null  int64
 9   MSRP               11914 non-null  int64
dtypes: float64(2), int64(4), object(4)
memory usage: 930.9+ KB

In [23]:
Data=Data.rename(columns ={"Engine HP": "HP","Engine Cylinders":"Cylinders",
                          "Driven_Wheels":"Drive Mode", "highway MPG":"HPG-H"})
Data.head()

,Make,Model,Year,HP,Cylinders,Transmission Type,Drive Mode,HPG-H,city mpg,MSRP
0,BMW,1 Series M,2011,335.0,6.0,MANUAL,rear wheel drive,26,19,46135
1,BMW,1 Series,2011,300.0,6.0,MANUAL,rear wheel drive,28,19,40650
2,BMW,1 Series,2011,300.0,6.0,MANUAL,rear wheel drive,28,20,36350
3,BMW,1 Series,2011,230.0,6.0,MANUAL,rear wheel drive,28,18,29450
4,BMW,1 Series,2011,230.0,6.0,MANUAL,rear wheel drive,28,18,34500

In [25]:
Data.shape

(11914, 10)

In [27]:
Duplication=Data[Data.duplicated()]
print("Numbers of Duplicates Rows",  Duplication.shape)

Numbers of Duplicates Rows (989, 10)

In [28]:
Data.count()

Make                 11914
Model                11914
Year                 11914
HP                   11845
Cylinders            11884
Transmission Type    11914
Drive Mode           11914
HPG-H                11914
city mpg             11914
MSRP                 11914
dtype: int64

In [30]:
Data=Data.drop_duplicates()
Data.count()

Make                 10925
Model                10925
Year                 10925
HP                   10856
Cylinders            10895
Transmission Type    10925
Drive Mode           10925
HPG-H                10925
city mpg             10925
MSRP                 10925
dtype: int64

In [31]:
print(Data.isnull().sum())

Make                  0
Model                 0
Year                  0
HP                   69
Cylinders            30
Transmission Type     0
Drive Mode            0
HPG-H                 0
city mpg              0
MSRP                  0
dtype: int64

In [32]:
Data=Data.dropna()

In [33]:
Data.count()

Make                 10827
Model                10827
Year                 10827
HP                   10827
Cylinders            10827
Transmission Type    10827
Drive Mode           10827
HPG-H                10827
city mpg             10827
MSRP                 10827
dtype: int64

In [34]:
print(Data.isnull().sum())

Make                 0
Model                0
Year                 0
HP                   0
Cylinders            0
Transmission Type    0
Drive Mode           0
HPG-H                0
city mpg             0
MSRP                 0
dtype: int64